version: "3.7"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile_frontend
      args:
        - "SERVER_ADDRESS=http://localhost:8080"
        - "PUBLIC_ADDRESS=http://localhost:3000"
    container_name: frontend
    environment:
      - "PORT=3000"
    depends_on:
      - backend
    restart: always
    ports:
      - 3000:3000
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile_backend
    container_name: backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128mb'
        reservations:
          cpus: '1'
          memory: '128mb'
    ports:
      - 8080:8080
