FROM node:10.16.3-alpine

ARG SERVER_ADDRESS
ARG PUBLIC_ADDRESS
ARG DEFAULT_GROUP

# libraries
# adapter
WORKDIR /usr/src/adapter
COPY ./adapter/package*.json ./
RUN npm install --only=production

# frontend
WORKDIR /usr/src/frontend
COPY ./frontend/package*.json ./
RUN npm remove adapter
RUN npm install --only=production

# compiling
# adapter
WORKDIR /usr/src/adapter
COPY ./adapter ./
RUN npm run build

# backend
WORKDIR /usr/src/frontend
RUN npm install --save ../adapter
COPY ./frontend ./
RUN REACT_APP_SERVER_ADDRESS=${SERVER_ADDRESS} \
    PUBLIC_URL=${PUBLIC_ADDRESS} \
    REACT_APP_DEFAULT_GROUP=${DEFAULT_GROUP}
    npm run build

EXPOSE 8080

CMD ["npm", "run", "production"]
