version: "3.5"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile_frontend
      args:
        - "SERVER_ADDRESS=http://localhost:8080"
        - "PUBLIC_ADDRESS=http://localhost:3000"
    container_name: frontend
    environment:
      - "PORT=3000"
    depends_on:
      - backend
    restart: always
    ports:
      - 3000:3000
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile_backend
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      - DB_URL=http://db:8000
      - FRONTEND_URL=http://localhost:3000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '128mb'
        reservations:
          cpus: '1'
          memory: '128mb'
    ports:
      - 8080:8080
  db:
    image: amazon/dynamodb-local
    container_name: db
    command: -jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data/
    volumes:
      - $DB_HOST_PERSIST_DIR:/home/dynamodblocal/data
    expose:
      - 8000
